### ISSUE TITLE
Fa schifo sto roba

### ISSUE THREAD

**Issue by dylanVanzan2000** [divino-marchese/zuccante#1]
Mi non capisco nulla de sta roba qua e poi quoi a mira in via bestie non ghe se segnal

**Comment by giovanniscanferla** [comment]
Con una grammatica del genere, un issue così può accompagnare solo.

**Comment by marcorossignoli20** [comment]
È un nuovo linguaggio di programmazione che non conosco?

**Comment by nicolabove** [comment]
Il browser mi ha fatto la traduziona automatica da "turco" a "italiano"

**Comment by nicolabove** [comment]
Traduzione

**Comment by Gemolo** [comment]
Spiego jesolo tu si è marghera no
